version: '3'

tasks:

  validate:
    desc: 'Validate the CWL workflow'
    cmds:
      - defer: rm -f process.json codemeta.json
      - |
        cwltool --validate cwl-workflow/open-sar-toolkit.cwl && \
        uv run --with transpiler-mate transpiler-mate codemeta cwl-workflow/open-sar-toolkit.cwl && \
        uv run --with cwl2ogc cwl2ogc --workflow-id opensartoolkit cwl-workflow/open-sar-toolkit.cwl
    silent: false

  metadata: 
    desc: 'Show CWL workflow metadata'
    cmds:
      - defer: rm -f codemeta.json
      - |
        uv run --with transpiler-mate transpiler-mate codemeta cwl-workflow/open-sar-toolkit.cwl
        cat codemeta.json
    silent: true 

  build:
    desc: 'Build the containers'
    cmds:
      - |
        cd command-line-tools/convert-search
        podman build -t convert-search:latest .
        cd ../stac-catalog
        podman build -t stac-catalog:latest .
    silent: false

  run: 
    desc: 'Run the convert-search CLI'
    cmds:
      - |
        cd command-line-tools/convert-search
        hatch run convert-search \
          --target-datetime 2024-11-14T00:00:00Z \
          --input-bbox "12.146,41.701,12.629,41.967" \
          --search-results discovery-output.json 
    silent: false

  run-cwl:
    desc: 'Run the opensartoolkit CWL workflow'
    vars:
      PARAMS_FILE:
        sh: mktemp
    cmds:
      - defer: rm -f "{{.PARAMS_FILE}}"
      - test -n "${CDSE_AWS_ACCESS_KEY_ID}" || (echo "CDSE_AWS_ACCESS_KEY_ID is not set" && exit 1)
      - test -n "${CDSE_AWS_SECRET_ACCESS_KEY}" || (echo "CDSE_AWS_SECRET_ACCESS_KEY is not set" && exit 1)
      - test -n "${CDSE_ENDPOINT_URL}" || (echo "CDSE_ENDPOINT_URL is not set" && exit 1)
      - task: build
      - |
        cat > "{{.PARAMS_FILE}}" <<'EOF'
        resolution: 100
        ard-type: 'OST_GTC'
        with-speckle-filter: "NO-FILTER"
        resampling-method: 'BILINEAR_INTERPOLATION' # 'BICUBIC_INTERPOLATION'

        target_datetime:
          value: "2024-11-12T00:00:00Z"

        bbox:
          class: https://raw.githubusercontent.com/eoap/schemas/main/geojson.yaml#Polygon
          type: Polygon
          bbox: [12.144804, 41.996186, 12.457839, 42.175561]
          coordinates: [[[12.144804, 41.996186],[12.457839, 41.996186],[12.457839, 42.175561],[12.144804, 42.175561],[12.144804, 41.996186]]]
        EOF
        cwltool \
          --preserve-environment CDSE_AWS_ACCESS_KEY_ID \
          --preserve-environment CDSE_AWS_SECRET_ACCESS_KEY \
          --preserve-environment CDSE_ENDPOINT_URL \
          cwl-workflow/open-sar-toolkit.cwl#opensartoolkit "{{.PARAMS_FILE}}"
    silent: false

  test:
    desc: Run tests
    cmds:
    - |
      cd command-line-tools/convert-search
      hatch run test:test-show-setup

      cd ../stac-catalog
      hatch run test:test-show-setup

  check:
    desc: Run code quality checks
    cmds:
    - |
      cd command-line-tools/convert-search
      hatch run dev:check
      cd ../stac-catalog
      hatch run dev:check

  lint:
    desc: Run linters
    cmds:
    - |
      cd command-line-tools/convert-search
      hatch run dev:lint
      cd ../stac-catalog
      hatch run dev:lint

  generate-docs:
    desc: Generate documentation
    cmds:
    - defer: rm -f docs/*/*.puml
    - |
      uv run --no-cache --with "transpiler-mate>=0.38.0" transpiler-mate markdown --workflow-id opensartoolkit --output docs --code-repository $(git remote get-url origin) cwl-workflow/open-sar-toolkit.cwl
      uv run --with cwl2puml cwl2puml --workflow-id opensartoolkit --output docs/opensartoolkit --convert-image --image-format svg cwl-workflow/open-sar-toolkit.cwl
      uv run --with cwl2puml cwl2puml --workflow-id s1_subworkflow --output docs/s1_subworkflow --convert-image --image-format svg cwl-workflow/open-sar-toolkit.cwl
